### ISSUE TITLE
Fixed failing cart page test

### ISSUE THREAD

**Issue by gedex** [woocommerce/wc-e2e-page-objects#33]
Found two failed tests when running the tests against the latest WC and Storefront:

```
  Cart page
    ✓ should displays no item in the cart (1027ms)
    ✓ should adds the product to the cart when "Add to cart" is clicked (1393ms)
    ✓ should increases item qty when "Add to cart" of the same product is clicked (1032ms)
    1) should updates qty when updated via qty input
    ✓ should remove the item from the cart when remove is clicked (21236ms)
    2) should update subtotal in cart totals when adding product to the cart
    ✓ should go to the checkout page when "Proceed to Checkout" is clicked (1130ms)


  5 passing (49s)
  2 failing

  1) Cart page should updates qty when updated via qty input:
     TimeoutError: Timed out waiting for element with css selector of 'input[name="update_cart"]' to be clickable
Wait timed out after 10168ms
      at node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:109:7)
  From: Task: Timed out waiting for element with css selector of 'input[name="update_cart"]' to be clickable
      at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Object.clickWhenClickable (node_modules/wp-e2e-webdriver/lib/helper.js:200:17)
      at CartPage.update (src/pages/cart-page.js:99:10)
      at Context.<anonymous> (test/cart-page.js:61:12)
      at runTest (node_modules/selenium-webdriver/testing/index.js:163:22)
      at node_modules/selenium-webdriver/testing/index.js:184:16
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1077:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:183:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2974:25)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
  From: Task: Cart page should updates qty when updated via qty input
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:182:10)

  2) Cart page should update subtotal in cart totals when adding product to the cart:
     TimeoutError: Timed out waiting for element with css selector of 'input[name="update_cart"]' to be clickable
Wait timed out after 10167ms
      at node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:109:7)
  From: Task: Timed out waiting for element with css selector of 'input[name="update_cart"]' to be clickable
      at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Object.clickWhenClickable (node_modules/wp-e2e-webdriver/lib/helper.js:200:17)
      at CartPage.update (src/pages/cart-page.js:99:10)
      at Context.<anonymous> (test/cart-page.js:95:12)
      at runTest (node_modules/selenium-webdriver/testing/index.js:163:22)
      at node_modules/selenium-webdriver/testing/index.js:184:16
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1077:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:183:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2974:25)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
  From: Task: Cart page should update subtotal in cart totals when adding product to the cart
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:182:10)
```

**Comment by gedex** [comment]
The culprit seems similar to #36 in which recent WC changed `input` to `button` for **Update Cart**.

/cc @claudiulodro @rodrigoprimo
