### ISSUE TITLE
Fixed failed checkout page test

### ISSUE THREAD

**Issue by gedex** [woocommerce/wc-e2e-page-objects#34]
Running against latest WC and Storefront:

```
  Checkout Page
    1) "before all" hook: ret


  0 passing (14s)
  1 failing

  1) Checkout Page "before all" hook: ret:
     TimeoutError: Timed out waiting for element with css selector of '.submit input[type="submit"]' to be clickable
Wait timed out after 10185ms
      at node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:109:7)
  From: Task: Timed out waiting for element with css selector of '.submit input[type="submit"]' to be clickable
      at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Object.clickWhenClickable (node_modules/wp-e2e-webdriver/lib/helper.js:200:17)
      at WPAdminWCSettingsGeneral.saveChanges (node_modules/wp-e2e-page-objects/lib/pages/wp-admin/wp-admin-settings.js:55:43)
      at StoreOwnerFlow.setGeneralSettings (src/flows/store-owner-flow.js:53:13)
      at Context.<anonymous> (test/checkout-page.js:49:14)
      at runTest (node_modules/selenium-webdriver/testing/index.js:163:22)
      at node_modules/selenium-webdriver/testing/index.js:184:16
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1077:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:183:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2974:25)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
  From: Task: Checkout Page "before all" hook: ret
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:182:10)
```

**Comment by gedex** [comment]
False alarm, this is fixed by PR for #36.
