### ISSUE TITLE
Failed tests on wp admin tax settings

### ISSUE THREAD

**Issue by gedex** [woocommerce/wc-e2e-page-objects#38]
Tested against latest WC and Storefront:

```
  WooCommerce Tax Settings
    1) can set tax options
    2) can add tax classes
    3) can set rate settings
    ✓ can remove tax classes (13559ms)


  1 passing (50s)
  3 failing

  1) WooCommerce Tax Settings can set tax options:
     TimeoutError: Timed out waiting for element with css selector of 'input[name="woocommerce_prices_include_tax"][value="no"]' to be clickable
Wait timed out after 10144ms
      at node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:109:7)
  From: Task: Timed out waiting for element with css selector of 'input[name="woocommerce_prices_include_tax"][value="no"]' to be clickable
      at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Object.clickWhenClickable (node_modules/wp-e2e-webdriver/lib/helper.js:200:17)
      at WPAdminWCSettingsTax.selectPricesEnteredWithNoTax (src/pages/wp-admin/wp-admin-wc-settings-tax.js:62:17)
      at Context.<anonymous> (test/wp-admin/wp-admin-wc-settings-tax.js:47:12)
      at runTest (node_modules/selenium-webdriver/testing/index.js:163:22)
      at node_modules/selenium-webdriver/testing/index.js:184:16
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1077:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:183:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2974:25)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
  From: Task: WooCommerce Tax Settings can set tax options
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:182:10)

  2) WooCommerce Tax Settings can add tax classes:
     TimeoutError: Timed out waiting for element with css selector of '#woocommerce_tax_classes' to be settable to: ''
Wait timed out after 10157ms
      at node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:109:7)
  From: Task: Timed out waiting for element with css selector of '#woocommerce_tax_classes' to be settable to: ''
      at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Object.setWhenSettable (node_modules/wp-e2e-webdriver/lib/helper.js:355:17)
      at WPAdminWCSettingsTax.removeAdditionalTaxClasses (src/pages/wp-admin/wp-admin-wc-settings-tax.js:111:17)
      at Context.<anonymous> (test/wp-admin/wp-admin-wc-settings-tax.js:63:12)
      at runTest (node_modules/selenium-webdriver/testing/index.js:163:22)
      at node_modules/selenium-webdriver/testing/index.js:184:16
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1077:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:183:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2974:25)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
  From: Task: WooCommerce Tax Settings can add tax classes
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:182:10)

  3) WooCommerce Tax Settings can set rate settings:
     TimeoutError: Timed out waiting for element with css selector of '.button.insert' to be clickable
Wait timed out after 10166ms
      at node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:109:7)
  From: Task: Timed out waiting for element with css selector of '.button.insert' to be clickable
      at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Object.clickWhenClickable (node_modules/wp-e2e-webdriver/lib/helper.js:200:17)
      at WPAdminWCSettingsTaxRates.insertRow (src/pages/wp-admin/wp-admin-wc-settings-tax-rates.js:171:17)
      at Context.<anonymous> (test/wp-admin/wp-admin-wc-settings-tax.js:76:12)
      at runTest (node_modules/selenium-webdriver/testing/index.js:163:22)
      at node_modules/selenium-webdriver/testing/index.js:184:16
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1077:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:183:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2974:25)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
  From: Task: WooCommerce Tax Settings can set rate settings
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:182:10)
```

**Comment by gedex** [comment]
false alarm, seems regression from #36.
