### ISSUE TITLE
Make create variation product test reliable

### ISSUE THREAD

**Issue by gedex** [woocommerce/wc-e2e-page-objects#9]
Got consistent failed test case as following (but happened sporadically):

```
  1) Add New Product Page can create product with variations:
     Error: Timed out waiting for element with css selector of '.woocommerce_variations .woocommerce_variation:nth-child(2) input[name^="variable_is_virtual"]' to be clickable
Wait timed out after 10002ms
      at node_modules/selenium-webdriver/lib/promise.js:2364:22
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1379:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2775:27)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: Timed out waiting for element with css selector of '.woocommerce_variations .woocommerce_variation:nth-child(2) input[name^="variable_is_virtual"]' to be clickable
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2352:17)
      at Driver.wait (node_modules/selenium-webdriver/lib/webdriver.js:712:29)
      at Object.clickWhenClickable (node_modules/wp-e2e-webdriver/lib/helper.js:72:16)
      at node_modules/wp-e2e-webdriver/lib/helper.js:85:18
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1379:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2775:27)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: Add New Product Page can create product with variations
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:128:10)
```

**Comment by claudiulodro** [comment]
I noticed this, too. It's some kind of a race condition or something with calling `toggle()` multiple times. I'll take a look at it.

**Comment by gedex** [comment]
@claudiulodro a hacky workaround would be:

```
driver.sleep( 500 );
```

the sleep can goes in core e2e after each call to `toggle()` or in this package inside `toggle()`. But still need to figure out a better way waiting the transition completes. Maybe watch the container class changes when toggled.

**Comment by claudiulodro** [comment]
After working on solving this problem some more, I don't think the problem is from `toggle()` after all.

I removed all the `toggle()`s from the test and added `helper.clickWhenClickable( driver, By.css( '#variable_product_options .expand_all' ) );` to click the "Expand" link and open all of the boxes instantly at the same time. I still get the error sometimes, even though all of the boxes are open.

After some more debugging, I am 90% sure the problem is that the checkbox isn't scrolled into view when selenium is trying to click on it. 

To test: 
1. Add `helper.scrollDown( driver ); helper.scrollDown( driver ); helper.scrollDown( driver );` right above `const var1 = panelVaritions.getRow( 1 );
`.
2. Run tests. Observe that it fails with the "Waiting to become clickable" error.

**Comment by gedex** [comment]
> After some more debugging, I am 90% sure the problem is that the checkbox isn't scrolled into view 

which checkbox?

can you try scroll to the element with:

~~~js
helper.mouseMoveTo( this.driver, SELECTOR );
~~~

i remembered having similar issue in checkout page https://github.com/woocommerce/wc-e2e-page-objects/blob/master/src/pages/checkout-page.js#L43
